version: '3'

services:
  producer:
    build: ./producer
    image: inventory-management-system-producer:latest
    volumes:
      - ./producer:/app
    depends_on:
      - database
      - rabbitmq
    network_mode: "host"  # Run in host network mode

  consumer_one:
    build: ./consumer_one
    image: inventory-management-system-consumer-one:latest
    volumes:
      - ./consumer_one:/app
    depends_on:
      - database
      - rabbitmq
    network_mode: "host"  # Run in host network mode

  # Add other services similarly

  rabbitmq:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
    network_mode: "host"  # Run in host network mode

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    network_mode: "host"  # Run in host network mode

volumes:
  postgres_data:
