version: "3.8"

networks:
  prodcon_network:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "15672:15672" # For RabbitMQ management interface
      - "5672:5672" # For RabbitMQ message broker
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      retries: 3
    networks:
      - prodcon_network

  producer:
    build: producer/
    ports:
      - "5000:5000" # For Flask server
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    networks:
      - prodcon_network

  consumer_health_check:
    build: consumer_one/
    depends_on:
      producer:
        condition: service_started
    networks:
      - prodcon_network

  consumer_insert_record:
    build: consumer_two/
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - prodcon_network

  consumer_delete_record:
    build: consumer_three/
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - prodcon_network

  consumer_read_database:
    build: consumer_four/
    command: python3 read_database.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - prodcon_network

  consumer_order:
    build: consumer_five/
    command: python3 order.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - prodcon_network